language: java
jdk: openjdk14

addons:
  sonarcloud:
    organization: "guilhermechiara"
    token:
      secure: "P+BknfYb/dVqcHA7ueGNTMvtBl6hIVJHQBySQUZgQt56EDIkQP9SAC9FlumMQoecCWCr8MRzpibNE6zbJtHUDl0N6Xg0hpfSVHRr+27EeIwaCNItiYmOmbqVXCk+YT3DZU1zjbbITtiDaxKEW+NDi2xYJQ4UcmtS9uRsFWd/nccFljS0j6WJqsdEeFoy90/9nhIpSpPP9hEBRZXg9R1gTH9n6551p
                5k0qkG9LJ2ZqT1Phy1i69MeTNBzHSf1Yv5R0VustLos1EgBK8FEUdmzladwl+FlWpDy1Ov5TLWrFkb8k/CBRrvXaNevoQDp5PHPvzIk7G/RvC7835RpJ7DzN/Ue/wzaAtPtUjYcpnniGj7RUct4MQWY5yJ9kno7n01kkBA+KJl8ZdHkVWMz+1d9XaszHwDkjPy5tXTbbPY85LqCKekG+wFrMSRZLYSlnmUPN/NJL
                UeWSUCV8LH2p+V1rUzROgP6mVK4VkB28eJc8dnNgJgg07hoblIcnLHW6o2U8rk+UBYv3xW4yhZya2Iaaq0NuIgEs0eM3jdVFebxbBS5sbMq2Wnvq/TIGRVU0oHZjtsAgWfs5Ii+lMwSFADIGa5yEQjMAQDIhU4at7u+HKhaFIpzX1aUZhV7G4ldCrGTQdSsy00lLhacTIeNHIP7/Kp47oOAex6EW+7/Wk6KHpc=" # encrypted value of your token

script:
  - ./gradlew sonarqube