language: java
jdk: openjdk14

addons:
  sonarcloud:
    organization: "guilhermechiara"
    token:
      secure: "wuO66G/WuJBjkPbOb4Gw9/7/FGj1RSssXHt0nyd6MrxcQ0JlvQft0RA9QD+XjdC501cRRGS8fpYNny3CmdVVSz/unUgXW4IjQdR5Uh3Occr44Ky9Bq9vGmCMUD+9izYgNug4D7ERhXZnOapR+2uqc+dX6EmpXEzxlmWUG5cgNfN5wM/clw29bmKamwn0b0xoWYZnxOHb85uovsmH43HMBMEeFPrcC
      UzUdyKGimVEJrtxo6i8cH6IkxFaPB4/UMmhSxV9GjiGevZH66OPIaPWzgYOFG4iNBX4MQpW/T3eg/+mAsawtbomETKTwnDjfj0q/XiML89Z0fmdgJhLk0uxxInaZFJ5DdRsjgFQfj23Y3rGuD/AHSZ+rpEESMzIM206Y95qBMfhBW8tJz0iczZRfDSK5vwWCr7xfjJAtkAm3ocLRq98vwCTu3GUW+Ez968jE+54B
      ddi+Ag4PBK/Et5b6VshglWpuXEPK8F23gaYXmK0kawhkRBKO9e/tbGLNMCT1ai01Z55Nxosc4LJ7LyM2mVhwEh3Ojd+hUFPfodaQ0OEFDRrBj6/ch9wcGi6IkEHLK+qchL45yobVKnLZzTN2BSYZBw6QlhZvruWrCGIVM/VMAU5QA8Ka6HYi17d5VRnhU+x+3yCwovFbvfrxXQ0F5RpR9aP2KmZ0VmMskL4utc="

script:
  - ./gradlew clean test build
  - ./gradlew sonarqube