language: java
jdk: openjdk14

addons:
  sonarcloud:
    organization: "guilhermechiara"
    token:
      secure: "0f124ef4a6db8aded3217a51c181ae3da3463aed" # encrypted value of your token

script:
  - ./gradlew sonarqube