language: java
jdk: openjdk14

addons:
  sonarcloud:
    organization: "guilhermechiara"
    token:
      secure: "b2s03Jmws8YUuAaRx6fv9ShJthRrefCVdbJ2eo1EKZ6lYv78NI2OkU4TeCeLQYReHTvEdrHTXj/PvX4QjVCV+RFfTGVGYkvC6ZuPHVapSs4EaKWVb+nuPx4klyMbZTMKU/qgOXxAFHrWX2AcNKgrDJbaY2vHq3pFfclrUUk3qzPxCvIi4kJ9rxuUuxDQ2roQBi7G1GqdhSudZMGbcHQ9exTO85CLM
      w1sIoIwrAwAxhQmmSHdng2qWnWlxtKfE/p68sBBnGgX4oxqzwsQf0B6RJT8u8fnwWBKuXzZsfgHEpmjkMG9NezD4lINBvSAMtuPvsrihlxlsww2MN7ggddrj+wzjkL+5+i4vfOdCSj3xFnPSXKMZf9UNRehf5n9TAoubFTvhufYENMqGCCrSpIQiz8iAbpx8YUVf2rj4hZ/AVj3kO9Tb4kYhgCnS12WwRG8VtsBc
      u4dkXhglL6N8oVAVZ9T2BB8FPZxScC57WUTIeE7PEePRdwAST1YIUEBd3m4SfdG8MpBYsljvVlRAdydP5kkGpX4eNedtsTzSfhTG8Uuy0IT/Cg9z2Ns6skARu7M3VAJqrH4r5GaCeUtqOetkB8D020RCyoALroPgxvB/l/zKhDO/7f25r+JeHYLJWMzWS4HiL6LM1IymHAeHQV7n6BxiBNfHXGe9Zwz1xLMeG0="

script:
  - ./gradlew sonarqube