spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/server"
    username: root
    password: chiara
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Custom path configuration
folders-config:
  data-path: data


